name: testing-shell-commands

on : [push]

jobs:
  testing-shell-commands:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Github-Actions"
      - name: multi-line-command
        run: |
          node -v
          npm -v
      - name: python-command
        run: |
          import platform
          print(platform.processor())
        shell: python

  testing-windows-commnd:
    runs-on: windows-latest
    steps:
      - name: run-powershell-command
        run: Get-Location
      - name: run-bash-command
        run: pwd
        shell: bash
